# Generated by Django 3.0.7 on 2020-06-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extinguisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('local_num', models.IntegerField()),
                ('last_check', models.TextField(max_length=8)),
                ('fire_state', models.IntegerField()),
            ],
        ),
    ]
